---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.11.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: 22.2.3-fpm-alpine
    nextcloud:
      host: "cloud.${SECRET_DOMAIN}"
      username: cloudadmin
      password: "${NEXTCLOUD_PASSWORD}"
      configs:
        local.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
            array (
              0 => '127.0.0.1',
              1 => '172.16.0.0/16',
            ),
            'forwarded_for_headers' =>
            array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
            'trashbin_retention_obligation' => 'auto, 30',
            'auth.bruteforce.protection.enabled' => true,
          );
      mail:
        enabled: true
        fromAddress: nullmailer
        domain: "${SECRET_DOMAIN}"
        smtp:
          host: imap.gmail.com
          secure: ssl
          port: 465
          authtype: LOGIN
          name: "nullmailer@${SECRET_DOMAIN}"
          password: "${NULLMAILLER_PASSWORD}"
    livenessProbe:
      initialDelaySeconds: 0
    readinessProbe:
      initialDelaySeconds: 0
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
    persistence:
      enabled: true
      existingClaim: nextcloud-data
    cronjob:
      enabled: true
      schedule: "*/15 * * * *"
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
        - secretName: "cloud.${SECRET_DOMAIN}"
          hosts:
            - "cloud.${SECRET_DOMAIN}"
    nginx:
      enabled: true
      config:
        default: true
    internalDatabase:
      enabled: false
    mariadb:
      enabled: true
      image:
        tag: 10.5.12-debian-10-r82
      rootUser:
        password: "${MARIA_ROOTPASSWORD}"
      db:
        name: nextcloud
        user: nextcloud
        password: "${NEXTCLOUD_DBPASSWORD}"
      replication:
        enabled: false
      master:
        persistence:
          enabled: true
          storageClass: ssd-iscsi-democratic
          size: 2Gi
    redis:
      enabled: true
      usePassword: true
      password: "${NEXTCLOUD_REDISPASSWORD}"
      cluster:
        enabled: false
      master:
        persistence:
          enabled: false
