apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: rootnode
  namespace: kube-system
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 192.168.1.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: rootnode-kubenet
  namespace: kube-system
spec:
  ipAddressPools:
  - kubenet-pool