---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.3
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    configInline:
      address-pools:
        - name: default
          protocol: bgp
          addresses:
            - "${METALLB_LB_RANGE}"
      peers:
        - peer-address: 192.168.1.1
          peer-asn: 64512
          my-asn: 64512
    controller:
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
    speaker:
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
