---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: storage
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: nobody
  password: "${TRUENAS_APIKEY}"
  backend: "${TRUENAS_IP}"
