---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: quadrant-media
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/HDD/Media
    server: "${TRUENAS_IP}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quadrant-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4000Gi
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: quadrant-media
